Repository xridge/kubestone, pull requests merged in 2019-08, with the labels that each got.

#7 ENH: Initial version of iperf3 stone
  cmd/manager/main.go
  config/crd/bases/perf.kubestone.xridge.io_networks.yaml
  config/default/kustomization.yaml
  controllers/iperf3/clientpod.go
  controllers/iperf3/controller.go
  controllers/iperf3/serverdeployment.go
  controllers/iperf3/serverservice.go
  go.sum
  pkg/k8s/client.go
  pkg/k8s/error.go
Labels: enhancement

#10 ENH: Add README.md [#2]
  README.md
Labels: documentation

#12 FIX: go-report warnings
  controllers/iperf3/controller.go
  controllers/iperf3/serverservice.go
Labels: bug

#9 ENH: Add Fio stone
  PROJECT
  api/v1alpha1/fio_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/perf.kubestone.xridge.io_fios.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_fios.yaml
  config/crd/patches/webhook_in_fios.yaml
  config/rbac/role.yaml
  config/samples/perf_v1alpha1_fio.yaml
  controllers/fio_controller.go
  controllers/suite_test.go
  main.go
Labels: enhancement, good first issue

#32 ENH: Use labels, affinity and image fields from CR
  api/v1alpha1/k8s_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/perf.kubestone.xridge.io_iperf3s.yaml
  config/samples/perf_v1alpha1_iperf3.yaml
  controllers/iperf3/clientpod.go
  controllers/iperf3/serverdeployment.go
  go.mod
  go.sum
Labels: enhancement

#35 FIX: add missing k8s resource permissions
  config/rbac/role.yaml
  controllers/fio_controller.go
  controllers/iperf3/clientpod.go
  controllers/iperf3/serverdeployment.go
  controllers/iperf3/serverservice.go
Labels: bug

#37 FIX: refer with full path to benchmark
  config/samples/perf_v1alpha1_fio.yaml
Labels: bug, good first issue

#36 ENH: Add anti-affinity rules to iperf so that client and server scheduled to different nodes
  config/samples/perf_v1alpha1_iperf3.yaml
Labels: enhancement, good first issue

#39 FIX: use one restClientConfig
  .gitignore
  main.go
Labels: enhancement, good first issue

#42 ENH: Add logo
  README.md
  images/kubestone-logo.png
Labels: documentation

#43 FIX: Kustomize 3.1.0 compatibility
  config/crd/kustomization.yaml
Labels: bug

#38 ENH: iperf3 complete workflow
  api/v1alpha1/iperf3_types.go
  config/crd/bases/perf.kubestone.xridge.io_iperf3s.yaml
  controllers/iperf3/clientpod.go
  controllers/iperf3/controller.go
  controllers/iperf3/serverdeployment.go
  controllers/iperf3/serverdeployment_test.go
  controllers/iperf3/serverservice.go
  controllers/iperf3/suite_test.go
  go.mod
  go.sum
  pkg/k8s/client.go
  pkg/k8s/eventrecorder.go
Labels: enhancement

#44 ENH: Extend developer documentation
  README.md
Labels: documentation

#49 ENH: Add tests for iperf3's clientpod and serverservice
  controllers/iperf3/clientpod_test.go
  controllers/iperf3/serverservice_test.go
Labels: enhancement :chart_with_upwards_trend:

#46 ENH: Refactored fio based on the recent iperf3 refactor
  api/v1alpha1/fio_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/perf.kubestone.xridge.io_fios.yaml
  config/samples/perf_v1alpha1_fio.yaml
  controllers/doc.go
  controllers/fio/controller.go
  controllers/fio/job.go
  controllers/fio/job_test.go
  controllers/fio/suite_test.go
  controllers/fio_controller.go
  main.go
Labels: api :fire:, enhancement :chart_with_upwards_trend:

#56 FIX: Add license header to controllers/fio/suite_test.go
  controllers/fio/suite_test.go
Labels: good first issue :beginner:

#57 FIX: Typo in controllers/iperf3/clientpod.go
  controllers/iperf3/clientpod.go
Labels: bug :bug:, documentation :books:

#58 ENH: Add code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation :books:

#59 ENH: Added vscode support
  .gitignore
  .vscode/launch.json
Labels: enhancement :chart_with_upwards_trend:

#61 ENH: Add kubebuilder.printcolumn to iperf3 status
  api/v1alpha1/iperf3_types.go
Labels: enhancement :chart_with_upwards_trend:

#63 ENH: Added pod configuration for fio
  api/v1alpha1/fio_types.go
  api/v1alpha1/iperf3_types.go
  api/v1alpha1/k8s_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/perf.kubestone.xridge.io_fios.yaml
  config/crd/bases/perf.kubestone.xridge.io_iperf3s.yaml
  controllers/fio/job.go
  controllers/fio/job_test.go
  controllers/iperf3/clientpod_test.go
  controllers/iperf3/serverdeployment_test.go
  controllers/iperf3/serverservice_test.go
Labels: api :fire:, enhancement :chart_with_upwards_trend:

#64 ENH: Generated sphinx documentation skeleton
  docs/Makefile
  docs/build/doctrees/environment.pickle
  docs/build/doctrees/index.doctree
  docs/build/html/.buildinfo
  docs/build/html/_sources/index.rst.txt
  docs/build/html/_static/alabaster.css
  docs/build/html/_static/basic.css
  docs/build/html/_static/custom.css
  docs/build/html/_static/doctools.js
  docs/build/html/_static/documentation_options.js
  docs/build/html/_static/file.png
  docs/build/html/_static/jquery-3.4.1.js
  docs/build/html/_static/jquery.js
  docs/build/html/_static/language_data.js
  docs/build/html/_static/minus.png
  docs/build/html/_static/plus.png
  docs/build/html/_static/pygments.css
  docs/build/html/_static/searchtools.js
  docs/build/html/_static/underscore-1.3.1.js
  docs/build/html/_static/underscore.js
  docs/build/html/genindex.html
  docs/build/html/index.html
  docs/build/html/objects.inv
  docs/build/html/search.html
  docs/build/html/searchindex.js
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation :books:

#62 ENH: Added support for PVCs for fio
  api/v1alpha1/fio_types.go
  api/v1alpha1/k8s_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/perf.kubestone.xridge.io_fios.yaml
  config/rbac/role.yaml
  config/samples/fio/overlays/pvc/kustomization.yaml
  config/samples/fio/overlays/pvc/patch.yaml
  controllers/fio/controller.go
  controllers/fio/job.go
  controllers/fio/job_test.go
  controllers/fio/pvc.go
  go.sum
Labels: api :fire:, enhancement :chart_with_upwards_trend:

#48 ENH: Create end-to-end test
  .circleci/config.yml
  Makefile
  config/rbac/role.yaml
  controllers/iperf3/serverdeployment.go
  controllers/iperf3/serverservice.go
  go.sum
  main.go
  tests/e2e/bin/deploy-kubestone.sh
  tests/e2e/bin/e2e-test-in-kind.sh
  tests/e2e/conf/kind-two-worker-cluster.yaml
  tests/e2e/fio_test.go
  tests/e2e/iperf3_test.go
  tests/e2e/suite_test.go
  tests/e2e/utils.go
Labels: enhancement :chart_with_upwards_trend:

#70 MAINT: Moved isJobFinished() to k8s.client
  controllers/fio/controller.go
  controllers/fio/job.go
  pkg/k8s/client.go
Labels: enhancement :chart_with_upwards_trend:

#73 ENH: Use hyperlinks in documentation
  docs/source/index.rst
  docs/source/install.md
  docs/source/quickstart.md
Labels: documentation :books:, enhancement :chart_with_upwards_trend:

#80 FIX: Removed build step from CircleCI
  .circleci/config.yml
Labels: enhancement :chart_with_upwards_trend:

#81 ENH: Use exact fio version
  config/samples/fio/base/fio_cr.yaml
Labels: enhancement :chart_with_upwards_trend:

#82 ENH: Reduce fio pvc size
  config/samples/fio/overlays/pvc/patch.yaml
Labels: enhancement :chart_with_upwards_trend:

#84 ENH: Add API Docs creator
  Makefile
  api/v1alpha1/doc.go
  docs/apidocs/NOTE
  docs/apidocs/config.json
  docs/apidocs/template/members.tpl
  docs/apidocs/template/pkg.tpl
  docs/apidocs/template/type.tpl
  docs/static/apidocs.html
Labels: api :fire:, documentation :books:

#90 ENH: Add google analytics
  mkdocs.yml
Labels: documentation :books:, enhancement :chart_with_upwards_trend:, good first issue

#91 FIX: Logo location in README.md
  README.md
Labels: bug :bug:, documentation :books:

#94 FIX: Iperf3 sample job link in documentation
  docs/benchmarks/iperf3.md
Labels: bug :bug:, documentation :books:, good first issue

#100 ENH: Add sysbench docs
  api/v1alpha1/sysbench_types.go
  config/crd/bases/perf.kubestone.xridge.io_sysbenches.yaml
  docs/benchmarks/status.md
  docs/benchmarks/sysbench.md
  docs/static/apidocs.html
  mkdocs.yml
Labels: documentation :books:, enhancement :chart_with_upwards_trend:

#102 FIX: Minimal kubernetes version to v1.13
  docs/quickstart.md
Labels: documentation :books:

#104 FIX: Use longer version of the Apache v2 License
  README.md
  docs/index.md
Labels: documentation :books:, enhancement :chart_with_upwards_trend:

#105 ENH: Exclude TODO creation for CRD objects
  .github/config.yaml
Labels: enhancement :chart_with_upwards_trend:

#107 FIX: Use correct filename for TODO bot config
  .github/config.yml
Labels: bug :bug:

#92 ENH: Added volume source support for fio
  api/v1alpha1/fio_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/perf.kubestone.xridge.io_fios.yaml
  config/samples/fio/base/fio_cr.yaml
  config/samples/fio/overlays/emptydir/kustomization.yaml
  config/samples/fio/overlays/emptydir/patch.yaml
  config/samples/fio/overlays/pvc/patch.yaml
  controllers/fio/controller.go
  controllers/fio/job.go
  controllers/fio/job_test.go
  controllers/fio/pvc.go
  docs/benchmarks/fio.md
  docs/quickstart.md
  docs/static/apidocs.html
Labels: api :fire:, enhancement :chart_with_upwards_trend:
