Repository xridge/kubestone, pull requests merged in 2019-09, with the labels that each got.

#111 ENH Added end to end test for fio
  config/samples/fio/overlays/custom_jobs/patch.yaml
  tests/e2e/fio_test.go
  tests/e2e/iperf3_test.go
  tests/e2e/suite_test.go
  tests/e2e/sysbench_test.go
Labels: enhancement :chart_with_upwards_trend:

#116 DOC: Deployment command in quickstart guide
  docs/quickstart.md
Labels: bug :bug:, documentation :books:

#115 FIX: Iperf3 connectivity in GKE
  config/rbac/role.yaml
  controllers/iperf3/clientjob.go
  controllers/iperf3/clientjob_test.go
  controllers/iperf3/controller.go
  controllers/iperf3/serverdeployment.go
  controllers/iperf3/serverservice.go
  pkg/k8s/client.go
  tests/e2e/iperf3_test.go
Labels: bug :bug:

#118 DOCS: Add Drill to the NAV Bar
  mkdocs.yml
Labels: bug :bug:, documentation :books:

#119 ENH: Added test to k8s.client + some refactor
  .vscode/launch.json
  main.go
  pkg/k8s/client_test.go
  pkg/k8s/eventrecorder.go
  pkg/k8s/suite_test.go
  tests/e2e/fio_test.go
Labels: enhancement :chart_with_upwards_trend:

#120 TST: Increase iperf3 e2e timeout to 90sec
  tests/e2e/iperf3_test.go
Labels: bug :bug:

#114 REF: Moved base job creation to common pkg
  api/v1alpha1/sysbench_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/common/job.go
  controllers/common/job_test.go
  controllers/drill/job.go
  controllers/drill/job_test.go
  controllers/fio/job.go
  controllers/fio/job_test.go
  controllers/iperf3/clientjob.go
  controllers/iperf3/clientjob_test.go
  controllers/sysbench/job.go
  controllers/sysbench/job_test.go
  docs/static/apidocs.html
Labels: enhancement :chart_with_upwards_trend:

#121 DOC: Remove iperf3 references from drill docs
  docs/benchmarks/drill.md
Labels: bug :bug:, documentation :books:

#125 ENH: Added resources support to pod config
  api/v1alpha1/k8s_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/perf.kubestone.xridge.io_drills.yaml
  config/crd/bases/perf.kubestone.xridge.io_fios.yaml
  config/crd/bases/perf.kubestone.xridge.io_iperf3s.yaml
  config/crd/bases/perf.kubestone.xridge.io_sysbenches.yaml
  controllers/common/job.go
  controllers/common/job_test.go
  controllers/common/suite_test.go
  controllers/iperf3/serverdeployment.go
  controllers/iperf3/serverdeployment_test.go
  controllers/iperf3/serverservice_test.go
  docs/static/apidocs.html
Labels: api :fire:, enhancement :chart_with_upwards_trend:

#136 MAINT: make resource labels consistent with FQDN
  controllers/common/job.go
  controllers/iperf3/serverdeployment.go
  controllers/iperf3/serverservice.go
Labels: enhancement :chart_with_upwards_trend:

#141 FIX: Include qperf CRD in kustomize build
  api/v1alpha1/qperf_types.go
  config/crd/bases/perf.kubestone.xridge.io_qperves.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_qperves.yaml
  config/crd/patches/webhook_in_qperves.yaml
  docs/static/apidocs.html
Labels: bug :bug:

#142 DOC: Fix ioping link name in docs
  docs/benchmarks/status.md
Labels: bug :bug:, documentation :books:

#143 DOC: Add reference to memory benchmark (via sysbench)
  docs/benchmarks/status.md
Labels: documentation :books:, enhancement :chart_with_upwards_trend:

#147 ENH: More idiomatic event reasons
  docs/quickstart.md
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/eventrecorder.go
Labels: enhancement :chart_with_upwards_trend:
